# Generated by Django 5.2.7 on 2025-11-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcardset_likes_userflashcardscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='type',
            field=models.CharField(choices=[('plain', 'Plain'), ('list', 'List')], default='plain', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserFlashcardScore',
        ),
    ]
